version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
      - VITE_SUPABASE_ANON_KEY=${VITE_SUPABASE_ANON_KEY}
      - VITE_STRIPE_PUBLIC_KEY=${VITE_STRIPE_PUBLIC_KEY}
      - VITE_STRIPE_BASIC_PRICE_ID=${VITE_STRIPE_BASIC_PRICE_ID}
      - VITE_STRIPE_PRO_PRICE_ID=${VITE_STRIPE_PRO_PRICE_ID}
      - VITE_STRIPE_PRO_PLUS_PRICE_ID=${VITE_STRIPE_PRO_PLUS_PRICE_ID}
      - VITE_STRIPE_ENTERPRISE_PRICE_ID=${VITE_STRIPE_ENTERPRISE_PRICE_ID}
    restart: unless-stopped
